"""Octo fine-tuning launcher.

Workflow
--------
1. Convert RoCo NPZ demos → RLDS TFRecord (via dataset_converter).
2. Generate an Octo finetune config Python file.
3. Launch ``python -m octo.scripts.finetune`` as a subprocess (or dry-run).
4. Write a run manifest and return a LaunchResult.

The Octo fine-tune script is the canonical entry point distributed with the
``octo`` package.  We invoke it as a module so that users don't need to clone
the Octo repo; the installed package is sufficient.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

from .config import OctoTrainingConfig


class OctoLaunchError(RuntimeError):
    pass


@dataclass
class LaunchResult:
    checkpoint_dir: str
    manifest_path: str
    command: List[str]
    status: str                 # "completed" | "dry_run" | "failed"
    num_steps_completed: int = 0


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _utc_now() -> str:
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).isoformat()


def _write_json(path: str, data: Dict[str, Any]) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2)
    os.replace(tmp, path)


def _generate_finetune_config(cfg: OctoTrainingConfig, rlds_dir: str) -> str:
    """Generate an upstream Octo ``scripts/finetune.py`` config."""
    pretrained_path = cfg.pretrained_path.replace("hf_hub:", "hf://", 1)
    action_mask = [True] * max(0, cfg.action_dim - 1) + [False]
    warmup_steps = min(2000, max(0, cfg.num_steps - 1))
    frozen_keys = "None"
    if cfg.frozen_keys and cfg.frozen_keys != "(?!.*hf_token).*vit.*":
        frozen_keys = repr((cfg.frozen_keys,))

    return textwrap.dedent(f"""\
        # Auto-generated by CRIE-Bench for Octo fine-tuning.
        # Task: {cfg.task_id}  Skill: {cfg.skill_id}  Agent: {cfg.agent_name}
        from ml_collections import ConfigDict
        from octo.model.components.action_heads import DiffusionActionHead
        from octo.model.components.tokenizers import LowdimObsTokenizer
        from octo.utils.spec import ModuleSpec

        def get_config(config_string="{cfg.finetune_config_mode}"):
            mode, task = config_string.split(",")
            assert mode in ["full", "head_only", "head_mlp_only"]
            assert task in ["image_conditioned", "language_conditioned", "multimodal"]

            if mode == "full":
                mode_frozen_keys = None
            elif mode == "head_only":
                mode_frozen_keys = ("octo_transformer.*",)
            else:
                mode_frozen_keys = (
                    "octo_transformer.*",
                    "heads_*.map_head.probe",
                    "heads_*.map_head.MultiHeadDotProductAttention_0.*",
                )

            frozen_keys_override = {frozen_keys}

            config = ConfigDict()
            config.dataset_kwargs = ConfigDict({{
                "name": "roco_{cfg.task_id}_{cfg.skill_id.lower()}",
                "data_dir": "{rlds_dir}",
                "image_obs_keys": {{"primary": "image_primary", "wrist": None}},
                "proprio_obs_key": "state",
                "language_key": "language_instruction",
                "action_proprio_normalization_type": "normal",
                "action_normalization_mask": {action_mask!r},
            }})
            config.pretrained_path = "{pretrained_path}"
            config.pretrained_step = None
            config.batch_size = {cfg.batch_size}
            config.shuffle_buffer_size = 10000
            config.num_steps = {cfg.num_steps}
            config.log_interval = {max(1, cfg.save_interval // 10)}
            config.eval_interval = {cfg.eval_interval}
            config.save_interval = {cfg.save_interval}
            config.save_dir = ""
            config.seed = {cfg.seed}
            config.wandb = ConfigDict({{"project": "octo_finetune", "group": None, "entity": None}})
            config.modality = task
            config.finetuning_mode = mode
            config.window_size = {cfg.window_size}
            config.optimizer = ConfigDict({{
                "learning_rate": ConfigDict({{
                    "name": "cosine",
                    "init_value": 0.0,
                    "peak_value": {cfg.lr},
                    "warmup_steps": {warmup_steps},
                    "decay_steps": {max(1, cfg.num_steps)},
                    "end_value": 0.0,
                }}),
                "weight_decay": 0.01,
                "clip_gradient": 1.0,
                "frozen_keys": frozen_keys_override if frozen_keys_override is not None else mode_frozen_keys,
                "grad_accumulation_steps": None,
            }})
            config.val_kwargs = ConfigDict({{
                "val_shuffle_buffer_size": 1000,
                "num_val_batches": 16,
            }})
            config.viz_kwargs = ConfigDict({{
                "eval_batch_size": max(1, min(128, {cfg.batch_size})),
                "trajs_for_metrics": 100,
                "trajs_for_viz": 8,
                "samples_per_state": 8,
            }})
            config.traj_transform_kwargs = ConfigDict({{
                "window_size": {cfg.window_size},
                "action_horizon": {cfg.chunk_size},
                "goal_relabeling_strategy": None,
                "task_augment_strategy": "delete_task_conditioning",
                "task_augment_kwargs": ConfigDict({{"keep_image_prob": 0.0}}),
            }})
            config.frame_transform_kwargs = ConfigDict({{
                "resize_size": {{"primary": (256, 256), "wrist": (128, 128)}},
                "image_augment_kwargs": {{}},
            }})
            config.frame_transform_threads = 16
            config.update_config = ConfigDict({{
                "model": ConfigDict({{
                    "observation_tokenizers": ConfigDict({{
                        "proprio": ModuleSpec.create(
                            LowdimObsTokenizer,
                            n_bins=256,
                            bin_type="normal",
                            low=-2.0,
                            high=2.0,
                            obs_keys=["proprio"],
                        ),
                    }}),
                    "heads": ConfigDict({{
                        "action": ModuleSpec.create(
                            DiffusionActionHead,
                            readout_key="readout_action",
                            use_map=False,
                            action_horizon={cfg.chunk_size},
                            action_dim={cfg.action_dim},
                            n_diffusion_samples=1,
                            dropout_rate=0.0,
                        ),
                    }}),
                }}),
            }})
            return config
    """)


def _find_upstream_finetune_script(cfg: OctoTrainingConfig) -> Optional[str]:
    candidates: List[str] = []
    if cfg.finetune_script:
        candidates.append(cfg.finetune_script)
    env_script = os.environ.get("OCTO_FINETUNE_SCRIPT", "")
    if env_script:
        candidates.append(env_script)
    for repo_dir in [cfg.octo_repo_dir, os.environ.get("OCTO_REPO_DIR", "")]:
        if repo_dir:
            candidates.append(str(Path(repo_dir) / "scripts" / "finetune.py"))

    try:
        import importlib.util
        spec = importlib.util.find_spec("octo")
        if spec is not None and spec.origin:
            package_dir = Path(spec.origin).resolve().parent
            candidates.append(str(package_dir.parent / "scripts" / "finetune.py"))
    except Exception:
        pass

    for candidate in candidates:
        if candidate and Path(candidate).is_file():
            return str(Path(candidate).resolve())
    return None


def _build_command(cfg: OctoTrainingConfig, config_file: str, output_dir: str) -> List[str]:
    script = _find_upstream_finetune_script(cfg)
    if script is None:
        script = "<octo_repo_dir>/scripts/finetune.py"
    command = [
        sys.executable, script,
        f"--config={config_file}:{cfg.finetune_config_mode}",
        f"--name={cfg.name}",
        f"--config.save_dir={output_dir}",
        f"--config.num_steps={cfg.num_steps}",
    ]
    if cfg.debug:
        command.append("--debug")
    return command


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def launch_octo_training(cfg: OctoTrainingConfig) -> LaunchResult:
    """Convert demos, write configs, launch Octo fine-tune, return manifest."""
    run_dir = Path(cfg.checkpoint_dir)
    manifest_path = str(run_dir / "run_manifest.json")

    if run_dir.exists() and (run_dir / "run_manifest.json").exists() and not cfg.overwrite:
        existing = json.loads((run_dir / "run_manifest.json").read_text())
        if existing.get("status") not in ("failed", "dry_run"):
            raise OctoLaunchError(
                f"Run directory already exists: {run_dir}. "
                "Use overwrite=True to re-run."
            )

    run_dir.mkdir(parents=True, exist_ok=True)

    # 1. Convert dataset (skip in dry-run)
    rlds_dir = cfg.resolved_rlds_dir
    if cfg.dry_run:
        print(f"  [1/3] Skipping dataset conversion (dry-run).")
        dataset_meta: Dict[str, Any] = {"backend": "dry_run"}
    else:
        print(f"  [1/3] Converting demos → RLDS ...")
        from integrations.octo_roco.dataset_converter import convert_demos
        convert_result = convert_demos(
            data_root=cfg.resolved_data_root,
            output_dir=rlds_dir,
            task_id=cfg.task_id,
            skill_id=cfg.skill_id,
            agent_name=cfg.agent_name,
            language_instruction=cfg.language_instruction,
            val_fraction=cfg.val_fraction,
            action_dim=cfg.action_dim,
            state_dim=cfg.state_dim,
        )
        print(f"       train={convert_result.num_train_episodes} eps  "
              f"val={convert_result.num_val_episodes} eps  "
              f"backend={convert_result.backend}")
        dataset_meta = {
            "num_train_episodes": convert_result.num_train_episodes,
            "num_val_episodes": convert_result.num_val_episodes,
            "total_steps": convert_result.total_steps,
            "backend": convert_result.backend,
        }

    # 2. Write finetune config file
    print(f"  [2/3] Writing Octo finetune config ...")
    config_file = str(run_dir / "finetune_config.py")
    finetune_cfg_str = _generate_finetune_config(cfg, rlds_dir)
    Path(config_file).write_text(finetune_cfg_str)

    # 3. Build command
    command = _build_command(cfg, config_file, str(run_dir))
    print(f"  [3/3] Training command:\n        {' '.join(command)}")

    # Write initial manifest
    manifest: Dict[str, Any] = {
        "name": cfg.name,
        "task_id": cfg.task_id,
        "skill_id": cfg.skill_id,
        "agent_name": cfg.agent_name,
        "pretrained_path": cfg.pretrained_path,
        "rlds_dir": rlds_dir,
        "checkpoint_dir": str(run_dir),
        "command": command,
        "config": cfg.to_dict(),
        "dataset": dataset_meta,
        "created_utc": _utc_now(),
        "status": "pending",
    }
    _write_json(manifest_path, manifest)

    if cfg.dry_run:
        manifest["status"] = "dry_run"
        manifest["end_utc"] = _utc_now()
        _write_json(manifest_path, manifest)
        print(f"\n  [dry_run] Would run: {' '.join(command)}")
        return LaunchResult(
            checkpoint_dir=str(run_dir),
            manifest_path=manifest_path,
            command=command,
            status="dry_run",
        )

    if command[1].startswith("<"):
        raise OctoLaunchError(
            "Could not find upstream Octo finetune script. Set "
            "OctoTrainingConfig.octo_repo_dir, OctoTrainingConfig.finetune_script, "
            "OCTO_REPO_DIR, or OCTO_FINETUNE_SCRIPT to an octo-models/octo checkout."
        )

    # 4. Run training
    manifest["status"] = "running"
    manifest["start_utc"] = _utc_now()
    _write_json(manifest_path, manifest)

    logs_dir = run_dir / "logs"
    logs_dir.mkdir(exist_ok=True)
    log_file = str(logs_dir / "train.log")
    print(f"\n  Training ... (log: {log_file})")

    try:
        env = os.environ.copy()
        compat_dir = Path(__file__).resolve().parents[1] / "upstream_compat"
        existing_pythonpath = env.get("PYTHONPATH", "")
        env["PYTHONPATH"] = (
            str(compat_dir)
            if not existing_pythonpath
            else str(compat_dir) + os.pathsep + existing_pythonpath
        )
        with open(log_file, "w") as log_fh:
            proc = subprocess.run(
                command,
                stdout=log_fh,
                stderr=subprocess.STDOUT,
                check=False,
                env=env,
            )
        returncode = proc.returncode
    except FileNotFoundError:
        raise OctoLaunchError(
            "Could not find upstream Octo 'scripts/finetune.py'. "
            "Set OCTO_REPO_DIR or OCTO_FINETUNE_SCRIPT."
        )

    status = "completed" if returncode == 0 else "failed"
    manifest["status"] = status
    manifest["end_utc"] = _utc_now()
    manifest["returncode"] = returncode
    _write_json(manifest_path, manifest)

    if returncode != 0:
        raise OctoLaunchError(
            f"Octo finetune exited with code {returncode}. "
            f"See log: {log_file}"
        )

    print(f"  Training complete. Checkpoint: {run_dir}")
    return LaunchResult(
        checkpoint_dir=str(run_dir),
        manifest_path=manifest_path,
        command=command,
        status=status,
        num_steps_completed=cfg.num_steps,
    )


def launch_from_config_path(path: str) -> LaunchResult:
    from .config import load_octo_training_config
    return launch_octo_training(load_octo_training_config(path))
