from typing import Optional, Sequence

from rocobench.skills.registry import SkillRegistry


class PlanningPromptProvider:
    """Interface for planner prompts used by prompters."""

    def get_action_prompt(self, obs, agent_name: Optional[str] = None) -> str:
        raise NotImplementedError

    def get_agent_prompt(self, obs, agent_name: Optional[str] = None) -> str:
        raise NotImplementedError


class LegacyPlanningPromptProvider(PlanningPromptProvider):
    """Default provider that delegates to the task environment."""

    def __init__(self, env) -> None:
        self.env = env

    def get_action_prompt(self, obs, agent_name: Optional[str] = None) -> str:
        del obs, agent_name
        return self.env.get_action_prompt()

    def get_agent_prompt(self, obs, agent_name: Optional[str] = None) -> str:
        if agent_name is None:
            return self.env.describe_obs(obs)
        return self.env.get_agent_prompt(obs, agent_name)


class PackGrocerySkillPromptProvider(PlanningPromptProvider):
    """Skill-mode prompt provider for PackGroceryTask."""

    def __init__(self, env, registry: SkillRegistry, agent_names: Sequence[str]) -> None:
        self.env = env
        self.registry = registry
        self.agent_names = list(agent_names)

    def get_action_prompt(self, obs, agent_name: Optional[str] = None) -> str:
        del obs
        if agent_name is None or agent_name not in self.agent_names:
            skills = []
            for name in self.agent_names:
                skills.append("{}:\n{}".format(name, self.registry.render_agent_skill_prompt(name)))
            skill_text = "\n\n".join(skills)
        else:
            skill_text = self.registry.render_agent_skill_prompt(agent_name)

        valid_objects = ", ".join(getattr(self.env, "item_names", []))
        valid_slots = ", ".join(getattr(self.env, "bin_slot_xposes", {}).keys())
        agent_lines = "\n".join(
            "NAME {} ACTION <SKILL_CALL>".format(name) for name in self.agent_names
        )
        return """[Task Objective]
Pack all grocery items into empty bin slots using high-level skills. The RRT backend will generate all low-level robot paths.

[Available Skills]
{skill_text}

Valid objects: {valid_objects}
Valid containers: {valid_slots}

[Skill Preconditions]
- PUT_OBJECT_IN_CONTAINER(object=<object>, container=<bin_slot>) targets one unpacked grocery item and one empty bin slot.
- If an agent already holds an object, it may place only that object.
- WAIT() keeps the robot stationary while another agent acts.

[Coordination Rules]
- Each agent must produce exactly one skill call.
- Do not assign the same object to two agents.
- Do not assign the same bin slot to two agents.
- Do not target an occupied bin slot.
- Do not output PICK, PLACE, MOVE, or PATH.
- Low-level paths are generated by the executor.

[Action Output Instruction]
EXECUTE
{agent_lines}

Valid example:
EXECUTE
NAME Alice ACTION PUT_OBJECT_IN_CONTAINER(object=apple, container=bin_front_left)
NAME Bob ACTION WAIT()
""".format(
            skill_text=skill_text,
            valid_objects=valid_objects,
            valid_slots=valid_slots,
            agent_lines=agent_lines,
        )

    def get_agent_prompt(self, obs, agent_name: Optional[str] = None) -> str:
        scene = self.env.describe_obs(obs)
        occupancy = {}
        if hasattr(self.env, "get_slot_occupancy"):
            occupancy = self.env.get_slot_occupancy(obs)
        occupancy_lines = []
        for slot_name in getattr(self.env, "bin_slot_xposes", {}).keys():
            occupant = occupancy.get(slot_name)
            occupancy_lines.append("{}: {}".format(slot_name, occupant if occupant is not None else "empty"))

        holding_lines = []
        for name in self.agent_names:
            held = None
            if hasattr(self.env, "get_agent_held_object"):
                held = self.env.get_agent_held_object(obs, name)
            holding_lines.append("{} holding: {}".format(name, held if held is not None else "nothing"))

        identity = "You are {}.\n".format(agent_name) if agent_name else ""
        return """{identity}[Current State]
{scene}

[Robot Holding State]
{holding}

[Bin Slot Occupancy]
{occupancy}

Choose high-level skills only. The final executable answer must strictly follow [Action Output Instruction].
""".format(
            identity=identity,
            scene=scene,
            holding="\n".join(holding_lines),
            occupancy="\n".join(occupancy_lines),
        )
